const catchAuthErr = require('./catchAuthErr')
module.exports = {
  catchAuthErr,
}
